#!/bin/bash
#  En val recogemos el valor entero de la RAM en búffer
#  -/+ buffers/cache:          [[0]]          6
#
#  # free -g
#               total       used       free     shared    buffers     cached
#  Mem:             7          5          1          0          0          4
#  -/+ buffers/cache:          0          6
#  Swap:            7          0          7
#
#  # awk '/^-/ {print $3}'
#  0


min=4
val=$(free -g | awk '/^-/ {print $3}')

/root/utilidades/scripts/Alertas/checkfeature ram $min $val

