#!/bin/bash
#  En val recogemos el valor entero del load de los ultimos 5 minutos (1,5,15)
#  load average: 0,01, [[0]],13, 0,22
#
#  # uptime
#  10:23:51 up 5 days, 20:14,  2 users,  load average: 0,01, 0,13, 0,22
#
#  # cut -d " " -f 14
#  0,13
#
#  # cut -d, -f1
#  0

min=4
val=$(uptime | cut -d " " -f 14 | cut -d, -f1)

/root/utilidades/scripts/Alertas/checkfeature cpu $min $val

